name: Healthcheck

on:
  schedule:
    # USTAWIENIE CZASU
    # Składnia: 'minuta godzina dzien miesiac dzien_tygodnia'
    # GitHub używa czasu UTC
    # */13 = co 13 minut
    # 8-19 = od 08:00 do 19:00 UTC
    - cron: '*/13 8-19 * * *'
  
  workflow_dispatch:

jobs:
  ping_services:
    runs-on: ubuntu-latest
    name: Ping URL List
    steps:
      - name: Ping URLs using Curl
        env:
          URLS: ${{ vars.PING_LIST }}
        run: |
          if [ -z "$URLS" ]; then
            echo "Lista URL jest pusta."
            exit 1
          fi

          for url in $URLS; do
            echo "--------------------------------"
            echo "Sprawdzam: $url"
            if curl -I -s --max-time 10 "$url" > /dev/null; then
              echo "SUKCES"
            else
              echo "BŁĄD"
            fi
          done
          echo "--------------------------------"
          echo "Koniec."